version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-CU14-ubuntu-20.04
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=StrongRootPassword2#
    expose:
      - '1433'
    networks:
      - backend

networks:
  backend:
    driver: bridge
    attachable: false
